
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB75pQrspkvXHqgbOpQ6Ba0C2RQZpGL7SU',
    appId: '1:1010420338510:web:301e008979ef152787181f',
    messagingSenderId: '1010420338510',
    projectId: 'fir-pooja-61114',
    authDomain: 'fir-pooja-61114.firebaseapp.com',
    storageBucket: 'fir-pooja-61114.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAooD86u9UaPsf8HUq317vBQlAl1wGdxcg',
    appId: '1:1010420338510:android:b6f0fab62d8d3ea687181f',
    messagingSenderId: '1010420338510',
    projectId: 'fir-pooja-61114',
    storageBucket: 'fir-pooja-61114.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsnbX0BKoNQjNqyodLj-4D6wEjtvwSuOo',
    appId: '1:1010420338510:ios:1b758435069aa73087181f',
    messagingSenderId: '1010420338510',
    projectId: 'fir-pooja-61114',
    storageBucket: 'fir-pooja-61114.firebasestorage.app',
    iosBundleId: 'com.example.myapp',
  );
}
