
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:razorpay_flutter/razorpay_flutter.dart';

import '../models/user.dart';
import '../models/booking.dart';
import '../models/pooja_package.dart';
import '../services/booking_service.dart';

class BookPoojaScreen extends StatefulWidget {
  final PoojaPackage poojaPackage;

  const BookPoojaScreen({super.key, required this.poojaPackage});

  @override
  State<BookPoojaScreen> createState() => _BookPoojaScreenState();
}

class _BookPoojaScreenState extends State<BookPoojaScreen> {
  final _formKey = GlobalKey<FormState>();
  DateTime? _selectedDate;
  final BookingType _bookingType = BookingType.online;
  final String _address = '';
  bool _isLoading = false;

  late Razorpay _razorpay;

  @override
  void initState() {
    super.initState();
    _razorpay = Razorpay();
    _razorpay.on(Razorpay.EVENT_PAYMENT_SUCCESS, _handlePaymentSuccess);
    _razorpay.on(Razorpay.EVENT_PAYMENT_ERROR, _handlePaymentError);
    _razorpay.on(Razorpay.EVENT_EXTERNAL_WALLET, _handleExternalWallet);
  }

  @override
  void dispose() {
    _razorpay.clear();
    super.dispose();
  }

  void _handlePaymentSuccess(PaymentSuccessResponse response) async {
    await BookingService().updateBookingPaymentStatus(
      response.orderId!,
      PaymentStatus.completed,
      response.paymentId,
    );
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(content: Text('Payment Successful')),
    );
    Navigator.pop(context);
  }

  void _handlePaymentError(PaymentFailureResponse response) async {
    await BookingService().updateBookingPaymentStatus(
      response.message!, // In case of failure, orderId is in message
      PaymentStatus.failed,
    );
    if (!mounted) return;
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(content: Text('Payment Failed: ${response.message}')),
    );
    setState(() {
      _isLoading = false;
    });
  }

  void _handleExternalWallet(ExternalWalletResponse response) {
    // Do something when an external wallet is selected
  }

  void _openCheckout(Booking booking, AppUser user) async {
    setState(() {
      _isLoading = true;
    });

    final options = {
      'key': 'YOUR_RAZORPAY_KEY_ID', // Replace with your key
      'amount': booking.price * 100, // Amount in paise
      'name': 'Pooja App',
      'description': widget.poojaPackage.name,
      'order_id': booking.id,
      'prefill': {'contact': user.email, 'email': user.email},
    };

    try {
      _razorpay.open(options);
    } catch (e) {
      debugPrint(e.toString());
    }
  }

  @override
  Widget build(BuildContext context) {
    final user = Provider.of<AppUser?>(context);

    return Scaffold(
      appBar: AppBar(
        title: Text('Book ${widget.poojaPackage.name}'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                // ... (rest of the form remains the same)

                ElevatedButton(
                  onPressed: _isLoading
                      ? null
                      : () async {
                          if (_formKey.currentState!.validate()) {
                            _formKey.currentState!.save();

                            if (_selectedDate == null) {
                              ScaffoldMessenger.of(context).showSnackBar(
                                const SnackBar(
                                  content: Text('Please select a date and time'),
                                ),
                              );
                              return;
                            }

                            final booking = Booking(
                              id: '', // Empty id, will be generated by firestore
                              userId: user!.id,
                              poojaId: widget.poojaPackage.id,
                              bookingType: _bookingType,
                              date: _selectedDate!,
                              status: BookingStatus.pending,
                              price: widget.poojaPackage.price,
                              paymentStatus: PaymentStatus.pending,
                              createdAt: DateTime.now(),
                              address: _address,
                            );

                            final newBooking = await BookingService().createBooking(booking);

                            _openCheckout(newBooking, user);
                          }
                        },
                  child: _isLoading
                      ? const CircularProgressIndicator()
                      : const Text('Confirm Booking'),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
